Docs:
  - changed-files:
      - any-glob-to-any-file:
          - webpage/**
          - "**/*.md"

GitHub Actions:
  - changed-files:
      - any-glob-to-any-file: ".github/**/*"

Python:
  - changed-files:
      - any-glob-to-any-file: "**/*.py"
