site_name: Electric demand data documentation
theme:
  name: material
  icon:
    logo: octicons/zap-24
    repo: octicons/git-branch-24
  favicon: zap-24.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: green
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - search.highlight
    - search.suggest

plugins:
  - privacy
  - search

repo_name: OET/electric-demand-data
repo_url: https://github.com/open-energy-transition/electric-demand-data
