[project]
name = "electric-demand-data"
version = "0.1.0"
description = "Electricity demand data"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "atlite>=0.4.0",
    "beautifulsoup4>=4.13.3",
    "cartopy>=0.24.1",
    "cdsapi>=0.7.5",
    "countryinfo>=0.1.2",
    "entsoe-py>=0.6.18",
    "geopandas>=1.0.1",
    "logging>=0.4.9.6",
    "matplotlib>=3.10.0",
    "mkdocs-material>=9.5.50",
    "numpy>=2.2.2",
    "pandas>=2.2.3",
    "pyarrow>=19.0.0",
    "pycountry>=24.6.1",
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
    "pytz>=2025.1",
    "shapely>=2.0.7",
    "timezonefinder>=6.5.8",
    "xarray>=2025.1.2",
]

[dependency-groups]
dev = [
    "pytest>=8.3.4",
    "pytest-cov>=6.0.0",
]

[tool.mypy]
ignore_missing_imports = true
disable_error_code = [
    "import-untyped"
    ]
files = [
  "ETL/**/*.py",
]

[tool.uv.workspace]
members = ["ETL"]
