target-version = "py312"

[lint] # See ruff documentation for more rules (https://docs.astral.sh/ruff/rules/).
# Add additional rules on top of the default `select` (`E4`, E7`, `E9`, and `F`).
extend-select = [
    "I", # sort imports
    "TID", # tidy imports
    "D", # tidy docstrings
]
# Define the convention for docstrings.
pydocstyle.convention = "numpy"

# Add specific rule codes/groups here to ignore them, or add a '#noqa' comment to the line of code to skip all checks.
ignore = []

[format]
docstring-code-format = true
docstring-code-line-length = 72
