# Configuration read by the forecast.py script.

# OPTIONAL.
# The machine learning algorithm to be used for forecasting.
model_path: 
data_path: "D:/Modelling/demandcast/demandcast/data/assembled/20260925/assembled_data_for_forecasting_20260925_131127.parquet"