# Zenodo metadata for datasets created by Open Energy Transition (OET).

creators:
  - name: "Antonini, Enrico G. A."
    affiliation: "Open Energy Transition"
    orcid: "0000-0002-5573-0954"

  - name: "Vamsi Priya, Goli"
    affiliation: "Open Energy Transition"

  - name: "Steijn, Kevin"

contributors:
  - name: "Open Energy Transition"
    type: "HostingInstitution"

  - name: "Breakthrough Energy"
    type: "Sponsor"
