# Configuration read by the train.py script.

# REQUIRED.
# Whether to reserve a set of data for later testing.
reserve_testing_set: true

# REQUIRED.
# Whether to use a validation set during training.
use_validation_set: false

# OPTIONAL.
# The path to the assembled data to be used for training.
data_path:
