name: Bug report
description: Report an error or unexpected behavior
labels: ["Bug"]

body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a bug, please make sure the issue hasn't been already
        addressed by searching through [the past issues](https://github.com/open-energy-transition/electric-demand-data/issues).

  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of the bug.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Please provide detailed steps to reproduce the bug.
        If we cannot reproduce the bug, it is unlikely that we will be able to help you.
    validations:
      required: true

  - type: input
    attributes:
      label: Version
      description: What commit/version are you using?
      placeholder: e.g., v0.0.1 (2af802e 2025-01-26)
    validations:
      required: true
