name: Feature request
description: Suggest a new feature or improvement
labels: ["Enhancement"]

body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a feature request, please make sure the request hasn't been already
        addressed by searching through [the past issues](https://github.com/open-energy-transition/demandcast/issues).

  - type: textarea
    attributes:
      label: Summary
      description: |
        A clear and concise description of what new feature or behavior you would like to see. If applicable, please describe the current behavior as well.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Example
      description: Provide an example of how the user experience would change or how the new feature would be used.
    validations:
      required: false
