name: Question
description: Ask a question about DemandCast
labels: ["Question"]
body:
  - type: markdown
    attributes:
      value: >
        #### Before submitting a question, please make sure it hasn't been already
        been asked by searching through [the past issues](https://github.com/open-energy-transition/demandcast/issues).

  - type: textarea
    attributes:
      label: Question
      description: Describe your question in detail.
    validations:
      required: true
